//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaDatabase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultimediaDatabase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap clear {
            get {
                object obj = ResourceManager.GetObject("clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbs.
        /// </summary>
        public static string DBS_TableName {
            get {
                return ResourceManager.GetString("DBS_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Directory {
            get {
                object obj = ResourceManager.GetObject("Directory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fileopen {
            get {
                object obj = ResourceManager.GetObject("fileopen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Green_Check {
            get {
                object obj = ResourceManager.GetObject("Green Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSize = File size
        ///OverallBitRate = Overall bit rate
        ///OverallBitRateMode = Overall bit rate mode
        ///BitDepth = Bit depth
        ///BitRate = Bit rate
        ///DisplayAspectRatio = Display aspect ratio
        ///FrameRateMode = Frame rate mode
        ///FrameRate = Frame rate
        ///Encoded_Application = Writing application
        ///StreamSize = Stream size
        ///SamplingRate = Sampling rate.
        /// </summary>
        public static string MediaInfoParameterDictionary {
            get {
                return ResourceManager.GetString("MediaInfoParameterDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filename.
        /// </summary>
        public static string MySQLTableColumn_Filename {
            get {
                return ResourceManager.GetString("MySQLTableColumn_Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filesize.
        /// </summary>
        public static string MySQLTableColumn_Filesize {
            get {
                return ResourceManager.GetString("MySQLTableColumn_Filesize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filetype.
        /// </summary>
        public static string MySQLTableColumn_Filetype {
            get {
                return ResourceManager.GetString("MySQLTableColumn_Filetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediaInfoHumanReadable.
        /// </summary>
        public static string MySQLTableColumn_MediaInfoHumanReadable {
            get {
                return ResourceManager.GetString("MySQLTableColumn_MediaInfoHumanReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediaInfoRawData.
        /// </summary>
        public static string MySQLTableColumn_MediaInfoRawData {
            get {
                return ResourceManager.GetString("MySQLTableColumn_MediaInfoRawData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OverallBitRate.
        /// </summary>
        public static string MySQLTableColumn_OverallBitRate {
            get {
                return ResourceManager.GetString("MySQLTableColumn_OverallBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to path.
        /// </summary>
        public static string MySQLTableColumn_Path {
            get {
                return ResourceManager.GetString("MySQLTableColumn_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        public static string MySQLTableColumn_Title {
            get {
                return ResourceManager.GetString("MySQLTableColumn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap play_button {
            get {
                object obj = ResourceManager.GetObject("play button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Red_Cross {
            get {
                object obj = ResourceManager.GetObject("Red Cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Remove_Item {
            get {
                object obj = ResourceManager.GetObject("Remove Item", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap retry {
            get {
                object obj = ResourceManager.GetObject("retry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
